audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log.txt"
music_directory    "~/Music"
auto_update "yes"
bind_to_address "~/mpdsocket"
